microservice-chart:
  image:
    repository: cstarucommonacr.azurecr.io/idpaypaymentinstrument
    tag: latest
    pullPolicy: Always

  ingress:
    host: "idpay.itn.internal.uat.cstar.pagopa.it"

  resources:
    requests:
      memory: "1Gi"
      cpu: "150m"
    limits:
      memory: "1Gi"
      cpu: "600m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envConfig:
    JAVA_TOOL_OPTIONS: >-
      -XX:InitialRAMPercentage=75.0
      -XX:MaxRAMPercentage=85.0
      -XX:+UseG1GC
      -XX:+UseContainerSupport
      -Djava.security.egd=file:/dev/./urandom
      -javaagent:/app/applicationinsights-agent.jar 
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json
    SCHEDULE_RETRIEVE_INITIATIVE: 0 0 */2 ? * *
    AZURE_KEYVAULT_URL: "https://cstar-u-idpay-kv.vault.azure.net"

  envSecret:
    aks-api-url: cstar-u-weu-uat01-aks-apiserver-url
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  keyvault:
    name: "cstar-u-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"