microservice-chart:
  image:
    repository: cstardcommonacr.azurecr.io/idpaypaymentinstrument
    tag: latest
    pullPolicy: Always

  ingress:
    host: "dev01.idpay.internal.dev.cstar.pagopa.it"

  resources:
    requests:
      memory: "768Mi"
      cpu: "1500m"
    limits:
      memory: "768Mi"
      cpu: "600m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envConfig:
    JAVA_TOOL_OPTIONS: "-Xms256m -Xmx512m -Djava.util.concurrent.ForkJoinPool.common.parallelism=7 -Dio.netty.eventLoopThreads=100 -javaagent:/app/applicationinsights-agent.jar -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3002 -Dcom.sun.management.jmxremote.rmi.port=3003 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
    SCHEDULE_RETRIEVE_INITIATIVE: 0 0 */2 ? * *
    AZURE_KEYVAULT_URL: "https://cstar-d-idpay-kv.vault.azure.net"

  envSecret:
    aks-api-url: cstar-d-weu-dev01-aks-apiserver-url
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  keyvault:
    name: "cstar-d-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"